import type { ReelPackage } from "../../../shared/reels";
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
export function reelComposition(reel:ReelPackage, duration:number, paths:Map<string,string>, cover=false) {
  const host=new URL(reel.source_url).hostname.replace(/^www\./, "").toUpperCase();
  const linkHost=new URL(reel.link_url).hostname.replace(/^www\./, "").toUpperCase();
  const heroArabic=reel.scenes.find(s=>s.kind==="search")?.arabic.split("←")[0].trim()||reel.keywords[0];
  const image=(id:string|null,cls="screen")=>id&&paths.has(id)?`<img class="${cls}" src="${esc(paths.get(id)!)}"/>`:"";
  const intro=reel.intro_id?paths.get(reel.intro_id):undefined;
  const sceneTimes=reel.scenes.map((s,i)=>({start:reel.scenes.slice(0,i).reduce((n,s)=>n+s.seconds,0)*duration/reel.target_seconds,duration:s.seconds*duration/reel.target_seconds}));
  const scenes=reel.scenes.map((s,i)=>{
    const time=sceneTimes[i];
    let visual="";
    if(s.kind==='hook') visual=`<div class="hero-shade"></div><div class="hero-orbit pill arabic">${esc(heroArabic)}</div><div class="hero-proof pill">ASL FE’LNI TOPING ↗</div><div class="hook-copy"><p class="eyebrow">${esc(host)} · FOYDALI IMKONIYAT</p><h1>${esc(reel.hook)}</h1><p class="subtitle">${esc(s.body)}</p></div>`;
    else if(s.kind==='search') visual=`<div class="query-card card"><span class="small">QIDIRILGAN SHAKL</span><div class="arabic query">${esc(s.arabic.split('←')[0]||s.arabic)}</div><div class="search-icon">⌕</div></div><div class="flow-arrow">↓</div><div class="result-card card"><span class="small">LUG‘ATDAGI ASL FE’L</span><div class="arabic">${esc(s.arabic.includes('←')?s.arabic.split('←')[1]:s.arabic)}</div><p>${esc(s.body)}</p><span class="verified">✓ Bir joyda: ma’no va tuslanish</span></div><div class="browser-window">${image(s.image_id)}<span class="browser-url">${esc(host)} · haqiqiy qidiruv</span></div>`;
    else if(s.kind==='example'||s.kind==='meaning') visual=`<div class="book-symbol">Aa<span class="arabic">ع</span></div><div class="example-card card"><span class="small">ARABCHA MISOL</span><div class="arabic">${esc(s.arabic)}</div><div class="divider"></div><span class="small">O‘ZBEKCHA MA’NO</span><p>${esc(s.body)}</p></div><div class="browser-window low">${image(s.image_id)}<span class="browser-url">Ma’noni misol bilan tushuning</span></div>`;
    else if(s.kind==='sarf') visual=`<div class="sarf-chips"><span>MOZIY</span><span>MUZORI’</span><span>AMR</span></div><div class="table-card card"><div class="arabic">${esc(s.arabic)}</div><p>${esc(s.body)}</p></div><div class="browser-window tall">${image(s.image_id)}<span class="browser-url">${esc(host)} · Sarf</span></div>`;
    else if(s.kind==='benefits') visual=`<div class="benefit-item card"><b>01</b><span>Harakat bilan</span><div class="arabic">${esc(s.arabic.split('•')[0]||s.arabic)}</div></div><div class="benefit-item card"><b>02</b><span>Harakatsiz</span><div class="arabic">${esc(s.arabic.split('•')[1]||'')}</div></div><div class="benefit-item card"><b>03</b><span>O‘zbekcha so‘z bilan</span><div class="latin-query">yozmoq ⌕</div></div><p class="benefit-note">${esc(s.body)}</p>`;
    else visual=`<div class="cta-title">HAVOLA<br><em>DIRECTGA!</em></div><div class="comment-card card"><div class="avatar">U</div><div><span class="small">IZOHGA YOZING</span><strong>${esc(reel.keywords[0])}</strong></div><span class="send-icon">↗</span></div><div class="flow-arrow">↓</div><div class="dm-card card"><span class="small">ZAMONAVIY TA’LIM · DIRECT</span><p>Material havolasi siz uchun</p><span class="link-chip">${esc(linkHost)} ↗</span></div><div class="follow-pill">${reel.require_follow?'✓ Avval profilga obuna bo‘ling':'Izoh qoldiring · Directni tekshiring'}</div>`;
    return `<section id="scene-${i}" class="scene ${s.kind}" data-start="${time.start}" data-duration="${time.duration}"><div class="scene-label">${String(i+1).padStart(2,'0')} / ${String(reel.scenes.length).padStart(2,'0')}</div>${!['hook','cta'].includes(s.kind)?`<h2>${esc(s.title)}</h2>`:''}${visual}</section>`;
  }).join('');
  const coverMarkup=`<section class="cover"><div class="cover-tag">${esc(host)} · ZAMONAVIY TA’LIM</div><h1>${esc(reel.hook)}</h1><div class="cover-art">${intro?`<video src="${esc(intro)}" muted data-start="0" data-duration="1" data-media-start="3.2"></video>`:''}</div><div class="cover-word card"><span class="small">TUSLANGAN SO‘Z → ASL FE’L</span><div class="arabic">${esc(reel.scenes.find(s=>s.kind==="search")?.arabic||heroArabic)}</div></div><div class="cover-benefits">MA’NO · MISOL · TUSLANISH</div><div class="cover-cta">Havola uchun <b>${esc(reel.keywords[0])}</b> yozing ↗</div></section>`;
  const timeline=cover?"tl.to({}, {duration:1});":`
  ${sceneTimes.map((t,i)=>`tl.fromTo('#scene-${i} h2', {y:55,opacity:0}, {y:0,opacity:1,duration:.55,ease:'power3.out'}, ${t.start+.08});
  tl.fromTo('#scene-${i} .card', {y:65,scale:.96,opacity:0}, {y:0,scale:1,opacity:1,stagger:.16,duration:.65,ease:'back.out(1.25)'}, ${t.start+.25});
  tl.fromTo('#scene-${i} .browser-window', {y:110,rotation:2,opacity:0}, {y:0,rotation:0,opacity:1,duration:.8,ease:'power3.out'}, ${t.start+.7});
  tl.to('#scene-${i} .browser-window img', {scale:1.035,duration:${Math.max(1,t.duration-1)},ease:'none'}, ${t.start+1});`).join('\n')}
  tl.fromTo('.hook-copy',{y:35,opacity:0},{y:0,opacity:1,duration:.7,ease:'power3.out'},.08);
  tl.fromTo('.hero-orbit',{scale:.4,y:60,rotation:-12,opacity:0},{scale:1,y:0,rotation:-6,opacity:1,duration:.8,ease:'back.out(1.4)'},1.1);
  tl.fromTo('.hero-proof',{y:40,opacity:0},{y:0,opacity:1,duration:.55},3.2);
  tl.fromTo('.cta-title',{y:60,opacity:0},{y:0,opacity:1,duration:.6},${sceneTimes.at(-1)!.start});
  tl.fromTo('.follow-pill',{scale:.7,opacity:0},{scale:1,opacity:1,duration:.7,ease:'back.out(1.4)'},${sceneTimes.at(-1)!.start+1.7});
  tl.fromTo('#progress',{scaleX:0},{scaleX:1,duration:${duration},ease:'none'},0);
  tl.to('.orb',{y:180,rotation:120,duration:${duration},ease:'none'},0);
  tl.to('.link-chip',{scale:1.04,repeat:3,yoyo:true,duration:.4,ease:'sine.inOut'},${sceneTimes.at(-1)!.start+4});`;
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'self' data: blob:; style-src 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self' ws:; font-src 'self' data:"><style>
  @font-face{font-family:Latin;src:url('latin.woff2');font-weight:100 900}@font-face{font-family:Arabic;src:url('arabic.woff2')}
  *{box-sizing:border-box}html,body{margin:0;width:1080px;height:1920px;overflow:hidden;background:#091d33;color:white;font-family:Latin,sans-serif}
  #root{position:relative;width:1080px;height:1920px;background:radial-gradient(ellipse at 85% 38%,#05696e 0,transparent 50%),radial-gradient(ellipse at 8% 88%,#194071 0,transparent 45%),#091d33;overflow:hidden}
  .grid{position:absolute;inset:0;background-image:linear-gradient(#ffffff07 1px,transparent 1px),linear-gradient(90deg,#ffffff07 1px,transparent 1px);background-size:90px 90px;transform:perspective(1100px) rotateX(8deg)}
  .orb{position:absolute;width:440px;height:440px;border:1px solid #4be7dd20;border-radius:50%;right:-100px;top:420px;box-shadow:0 0 100px #3bdedc20,inset 0 0 70px #3bdedc10}
  header{position:absolute;top:72px;left:76px;right:86px;display:flex;justify-content:space-between;align-items:center;z-index:50;font-size:22px;font-weight:700;letter-spacing:2px}header b{background:#30dac5;color:#072934;padding:13px 17px;border-radius:15px;letter-spacing:0}
  .scene{position:absolute;inset:0;padding:195px 76px 170px;overflow:hidden}.scene-label{color:#93b6c2;font-size:22px;letter-spacing:4px;margin-bottom:26px}h2{font-size:72px;line-height:1.12;letter-spacing:-2px;margin:0 0 52px;font-weight:900;max-width:820px}
  .card{border-radius:35px;background:#f7fafc;color:#102d43;padding:36px;border:2px solid #ffffffaa;box-shadow:0 24px 48px #0004}
  .small{font-size:21px;letter-spacing:2px;color:#5d7888;font-weight:800;display:block}.arabic{font-family:Arabic;direction:rtl;font-size:84px;line-height:1.55;font-weight:400;text-align:center;letter-spacing:0}.card p{font-size:38px;line-height:1.3;margin:20px 0}
  .hero-video{position:absolute;top:375px;left:0;width:1080px;height:1520px;object-fit:cover}.hero-shade{position:absolute;inset:0;background:linear-gradient(#091d33 0%,#091d33ef 21%,#091d3300 44%,#091d3300 76%,#091d33 96%)}.hook-copy{position:absolute;top:195px;left:76px;right:76px}.eyebrow{color:#58ddcf;font-size:24px;font-weight:800;letter-spacing:3px;margin:0 0 20px}h1{font-size:92px;line-height:1.05;letter-spacing:-3px;font-weight:900;margin:0}.subtitle{font-size:34px;color:#ffdf7b;font-weight:700;margin-top:30px}.pill{position:absolute;padding:16px 25px;border-radius:24px;background:#ffdf7b;color:#082f40;font-weight:800;box-shadow:0 14px 30px #0004}.hero-orbit{top:1180px;left:85px;font-size:74px;transform:rotate(-6deg)}.hero-proof{top:1560px;right:83px;font-size:24px;transform:rotate(4deg)}
  .query-card{position:relative}.query{font-size:108px;color:#008c80}.search-icon{position:absolute;right:38px;top:68px;font-size:70px;color:#008c80}.flow-arrow{text-align:center;color:#ffdb72;font-size:70px;height:100px;line-height:100px}.result-card .arabic{font-size:71px}.result-card p{margin:6px 0 16px;text-align:center}.verified{display:block;background:#d3f5eb;color:#147664;border-radius:15px;text-align:center;padding:13px;font-size:24px;font-weight:800}
  .browser-window{position:relative;overflow:hidden;border:9px solid #658087;border-radius:32px;background:white;height:475px;margin-top:34px;box-shadow:0 25px 70px #0005}.screen{width:100%;height:100%;object-fit:contain;object-position:50% 0;display:block}.browser-url{position:absolute;bottom:0;left:0;right:0;background:#0c293bde;color:#b9efe7;text-align:center;font-size:22px;padding:14px;z-index:2}.book-symbol{margin:10px auto 35px;width:140px;height:120px;border-radius:20px;background:#33d6bf;color:#0c3144;transform:rotate(-8deg);font-size:52px;font-weight:900;display:flex;align-items:center;justify-content:space-around;box-shadow:18px 14px 0 #1a7180}.book-symbol .arabic{font-size:57px}.example-card{text-align:center;padding:48px 30px}.example-card .arabic{font-size:98px;margin:17px 0}.example-card p{font-size:46px;font-weight:800}.divider{height:2px;background:#d6e1e7;margin:24px 30px}.low{height:485px;margin-top:45px}
  .sarf-chips{display:flex;gap:18px;margin-bottom:28px}.sarf-chips span{background:#ffdf7b;color:#163143;font-size:25px;font-weight:900;border-radius:15px;padding:15px 20px}.table-card{text-align:center}.table-card .arabic{font-size:78px}.table-card p{font-size:27px}.tall{height:900px;margin-top:40px}.tall .screen{object-fit:contain;object-position:50% 0}
  .benefit-item{margin-bottom:30px;position:relative;padding:35px 35px 25px}.benefit-item b{display:inline-block;background:#009886;color:white;border-radius:15px;padding:12px;font-size:24px;margin-right:18px}.benefit-item span{font-size:33px;font-weight:800}.benefit-item .arabic{font-size:87px}.latin-query{text-align:center;font-size:52px;color:#008c80;font-weight:800;margin:25px 0 8px}.benefit-note{font-size:29px;color:#bbd8e2;line-height:1.4}
  .cta-title{font-size:110px;line-height:1.06;font-weight:900;letter-spacing:-3px;margin-bottom:75px}.cta-title em,h1 em{font-style:normal;color:#ffde77}.comment-card{display:flex;align-items:center;gap:28px}.avatar{background:#d7f4eb;color:#08776e;width:100px;height:100px;border-radius:50%;display:grid;place-items:center;font-size:48px;font-weight:900}.comment-card strong{display:block;color:#008e80;font-size:92px;line-height:1.2}.send-icon{margin-left:auto;font-size:65px}.dm-card{background:#c9fae7}.dm-card p{font-size:33px;font-weight:800}.link-chip{background:#0c5260;color:#a9f8e0;display:inline-block;font-size:34px;padding:22px;border-radius:18px}.follow-pill{margin:70px auto 0;background:#ffde77;color:#183340;border-radius:25px;padding:25px;text-align:center;font-size:31px;font-weight:900}
  footer{position:absolute;bottom:90px;left:76px;right:90px;color:#97b7c6;font-size:21px;z-index:60;display:flex;justify-content:space-between}footer span:last-child{font-size:19px}#progress{position:absolute;bottom:55px;left:76px;width:914px;height:7px;background:#37dac6;border-radius:5px;transform-origin:left;z-index:61}
  .cover{position:absolute;inset:0;padding:235px 70px 165px}.cover-tag{font-size:26px;font-weight:800;color:#7ce9d4;letter-spacing:2px;margin-bottom:37px}.cover h1{font-size:80px;line-height:1.15;letter-spacing:-3px}.cover-art{height:620px;position:relative;overflow:hidden;border-radius:55px;margin-top:35px;box-shadow:0 30px 90px #0007}.cover-art video{width:100%;height:100%;object-fit:cover;object-position:center 38%}.cover-word{position:relative;margin:-110px 40px 0;background:#fff7d6;transform:rotate(-3deg)}.cover-word .arabic{font-size:78px;color:#094e59}.cover-benefits{text-align:center;color:#70e4d5;font-size:28px;font-weight:900;margin-top:60px;letter-spacing:1px}.cover-cta{text-align:center;font-size:29px;margin-top:40px}.cover-cta b{color:#ffdf7b}
  </style></head><body><div id="root" data-composition-id="root" data-width="1080" data-height="1920" data-duration="${cover?1:duration}" data-fps="30"><div class="grid"></div><div class="orb"></div><header><b>Z</b><span>ZAMONAVIY TA’LIM</span></header>${!cover&&intro?`<video class="hero-video" src="${esc(intro)}" muted playsinline data-start="0" data-duration="${sceneTimes[0].duration}"></video>`:""}${cover?coverMarkup:scenes}<footer><span>ARAB TILI · YANGI IMKONIYAT</span><span>U. Abdurayimov</span></footer>${cover?'':'<div id="progress"></div>'}</div><script src="gsap.min.js"></script><script>const tl=gsap.timeline({paused:true});${timeline}window.__timelines={root:tl};</script></body></html>`;
}
