import { useState } from "react";
import { mediaApi, type MediaData } from "./api";
import { explainerPlanSchema, type ExplainerPlan } from "@shared/explainer";
import type { MediaPost } from "@shared/media";
const empty = (): ExplainerPlan => ({title:"Fikr bildirishning 5 usuli",source_post_id:null,music_id:null,scenes:[{title:"Fikringizni arabcha qanday bildirasiz?",arabic:"",translation:"Bugun 5 ta foydali iborani o‘rganamiz.",narration:"Fikringizni arabcha qanday bildirasiz? Bugun beshta foydali iborani o‘rganamiz. Oxirida kichik mashq ham bor.",image_id:null,motion:"pop",sfx:"pop"},{title:"Menimcha…",arabic:"فِي رَأْيِي، …",translation:"Mening fikrimcha…",narration:"Birinchi ibora: فِي رَأْيِي. O‘zbekchasi: mening fikrimcha. Endi iborani ovoz chiqarib takrorlang.",image_id:null,motion:"slide",sfx:"whoosh"}]});
type Voice = { id:string;name:string;category:string;labels:Record<string,string> };
export default function ExplainerStudio({data,onSaved}:{data:MediaData;onSaved:()=>Promise<unknown>}) {
  const [plan,setPlan]=useState(empty),[id,setId]=useState(""),[topic,setTopic]=useState("Fikr bildirishning 5 usuli"),[voices,setVoices]=useState<Voice[]>([]),[voice,setVoice]=useState(""),[approved,setApproved]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
  const saved=data.posts.find(p=>p.id===id), jobs=data.jobs.filter(j=>j.kind==="explainer"&&j.payload?.post_id===id), active=jobs.some(j=>["queued","running"].includes(j.status)), locked=busy||active;
  const images=data.assets.filter(a=>["image/jpeg","image/png"].includes(a.mime_type));
  const change=(next:ExplainerPlan)=>{setPlan(next);setApproved(false);setNotice("");};
  async function action(fn:()=>Promise<void>){setBusy(true);setError("");try{await fn();}catch(e){setError(e instanceof Error?e.message:"Amal bajarilmadi.");}finally{setBusy(false);}}
  async function save(){const p=explainerPlanSchema.parse(plan);const previous=data.posts.find(p=>p.id===id);const unchanged=JSON.stringify(previous?.variants.explainer)===JSON.stringify(p);const variants={...previous?.variants,explainer:p};if(!unchanged){delete variants.explainer_video_id;delete variants.explainer_audio_id;}const post=await mediaApi<MediaPost>(id?`/posts/${id}`:"/posts",id?"PATCH":"POST",{title:p.title,caption:topic,format:"video",asset_ids:unchanged&&previous?.variants.explainer_video_id?[previous.variants.explainer_video_id]:Array.from(new Set(p.scenes.flatMap(s=>s.image_id?[s.image_id]:[]))),variants,production_notes:"Explainer ssenariysi va sahnalar rejasi:\n"+JSON.stringify(p,null,2)});setId(post.id);await onSaved();return post.id;}
  function load(value:string){const post=data.posts.find(p=>p.id===value);setId(value);setPlan(post?.variants.explainer||empty());setTopic(post?.caption||"Fikr bildirishning 5 usuli");setApproved(false);setError("");setNotice("");}
  return <div className="space-y-5">
    <section className="media-panel space-y-4"><h2>Explainer video studiyasi</h2><p>Avval post va ssenariy, keyin tasdiqlash, klon ovoz va audioga mos 9:16 MP4. Sahna vaqtlari tayyor ovozdan hisoblanadi.</p>
      <label className="block">Video loyihasi<select className="media-input" disabled={locked} value={id} onChange={e=>load(e.target.value)}><option value="">Yangi loyiha</option>{data.posts.filter(p=>p.variants.explainer).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>
      <label className="block">Manba post<select className="media-input" disabled={locked} value={plan.source_post_id||""} onChange={e=>change({...plan,source_post_id:e.target.value||null})}><option value="">Mavzu bo‘yicha yangi ssenariy</option>{data.posts.filter(p=>!p.variants.explainer).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>
      <label className="block">Mavzu va o‘quv maqsadi<textarea className="media-input" maxLength={3000} value={topic} disabled={locked} onChange={e=>setTopic(e.target.value)}/></label>
      <button className="media-btn" disabled={locked||topic.trim().length<3} onClick={()=>void action(async()=>{const result=await mediaApi<ExplainerPlan>("/explainer/plan","POST",{topic,source_post_id:plan.source_post_id});change(result);setNotice("Ssenariy tayyor. Matn va rasmlarni tekshirib tasdiqlang.");})}>{busy?"Bajarilmoqda…":"AI ssenariy rejasini tuzish"}</button><p className="text-sm">Bu bosqich audio yoki video yaratmaydi. Quyidagi dastlabki 2 sahna tahrirlash uchun namuna; to‘liq dars emas.</p>
    </section>
    <section className="media-panel space-y-4"><label className="block">Video nomi<input className="media-input" maxLength={100} disabled={locked} value={plan.title} onChange={e=>change({...plan,title:e.target.value})}/></label>
    {plan.scenes.map((scene,i)=><fieldset key={i} disabled={locked} className="media-panel space-y-3"><div className="media-actions"><h3>{i+1}-sahna</h3><button className="media-btn secondary small" disabled={plan.scenes.length<=2||locked} onClick={()=>change({...plan,scenes:plan.scenes.filter((_,n)=>n!==i)})}>O‘chirish</button></div>
      {([['title','Ekrandagi sarlavha',100],['arabic','Arabcha misol (harakatlari bilan)',240],['translation','O‘zbekcha izoh',240],['narration','Narrator o‘qiydigan matn',600]] as const).map(([key,label,max])=><label className="block" key={key}>{label}<textarea className="media-input" dir={key==='arabic'?'rtl':'ltr'} lang={key==='arabic'?'ar':'uz'} value={scene[key]} maxLength={max} onChange={e=>change({...plan,scenes:plan.scenes.map((s,n)=>n===i?{...s,[key]:e.target.value}:s)})}/></label>)}
      <label className="block">Post rasmi / ikon<select className="media-input" value={scene.image_id||""} onChange={e=>change({...plan,scenes:plan.scenes.map((s,n)=>n===i?{...s,image_id:e.target.value||null}:s)})}><option value="">Sodda belgi</option>{images.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
      {scene.image_id&&<img alt="Sahna rasmi" src={`/api/media/assets/${scene.image_id}`} className="h-32 rounded-xl object-contain"/>}
      <div className="grid sm:grid-cols-2 gap-3"><label>Harakat<select className="media-input" value={scene.motion} onChange={e=>change({...plan,scenes:plan.scenes.map((s,n)=>n===i?{...s,motion:e.target.value as typeof s.motion}:s)})}><option value="pop">Pop / yumshoq sakrash</option><option value="slide">Slide / siljish</option><option value="zoom">Zoom / yaqinlashish</option></select></label><label>Ovoz effekti<select className="media-input" value={scene.sfx} onChange={e=>change({...plan,scenes:plan.scenes.map((s,n)=>n===i?{...s,sfx:e.target.value as typeof s.sfx}:s)})}>{['pop','whoosh','tick','typing','none'].map(s=><option key={s}>{s}</option>)}</select></label></div>
    </fieldset>)}
    <button className="media-btn secondary" disabled={locked||plan.scenes.length>=8} onClick={()=>change({...plan,scenes:[...plan.scenes,{title:"Yangi sahna",arabic:"",translation:"",narration:"",image_id:null,motion:"pop",sfx:"pop"}]})}>+ Sahna qo‘shish</button>
    <p>Jami narrator matni: {plan.scenes.reduce((n,s)=>n+s.narration.length,0)} / 2000 belgi. 2–8 sahna, har sahnada bitta fikr.</p>
    <label className="block">Fon musiqa<select className="media-input" disabled={locked} value={plan.music_id||""} onChange={e=>change({...plan,music_id:e.target.value||null})}><option value="">Musiqasiz</option>{data.assets.filter(a=>a.mime_type==='audio/mpeg').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
    <div className="media-actions"><button className="media-btn secondary" disabled={locked} onClick={()=>void action(async()=>{await save();setNotice("Reja saqlandi.");})}>Rejani saqlash</button><button className="media-btn secondary" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(plan,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='explainer-reja.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Montaj rejasini yuklab olish</button></div>
    </section>
    <section className="media-panel space-y-4"><h2>Ovoz va video yaratish</h2><p>ElevenLabs v4 · O‘zbek tili · Arabcha va o‘zbekcha matnni bitta tanlangan ovoz o‘qiydi.</p><button className="media-btn secondary" disabled={locked} onClick={()=>void action(async()=>{const c=await mediaApi<{voices:Voice[]}>("/audio/catalog");setVoices(c.voices);setVoice(c.voices.find(v=>/umidjon/i.test(v.name))?.id||c.voices[0]?.id||"");})}>Ovozlarni yuklash</button>
    <label className="block">Narrator<select className="media-input" disabled={locked} value={voice} onChange={e=>setVoice(e.target.value)}><option value="">Ovozni tanlang</option>{voices.map(v=><option key={v.id} value={v.id}>{v.name}{['professional','cloned'].includes(v.category)?' · Klon':''}</option>)}</select></label>
    <label className="flex gap-2"><input type="checkbox" checked={approved} disabled={locked} onChange={e=>setApproved(e.target.checked)}/>Ssenariy va media rejasini tasdiqlayman.</label>
    <button className="media-btn" disabled={locked||!approved||!voice} onClick={()=>void action(async()=>{const postId=await save();await mediaApi("/explainer/render","POST",{post_id:postId,voice_id:voice,approved:true});setApproved(false);setNotice("Video navbatga qo‘yildi. Bu sahifaga keyin qaytib ham natijani ko‘rishingiz mumkin.");await onSaved();})}>{active?'Video tayyorlanmoqda…':'Klon ovoz va MP4 yaratish'}</button>
    <p className="text-sm">Post rasmlariga harakat, alohida arabcha matn va SFX qo‘shiladi. Yangi 3D qahramon animatsiyasi bu rendererda yaratilmaydi. ElevenLabs sarfi bor; kanalga yuborish alohida bajariladi.</p>
    {jobs.map(j=><div key={j.id}><p>{j.status==='queued'?'Navbatda':j.status==='running'?'Ovoz va sahnalar yaratilmoqda':j.status==='completed'?'Video tayyor':j.status==='failed'?'Jarayon bajarilmadi':j.status}</p>{j.error&&<p role="alert">{j.error}</p>}{j.result?.timings&&<div className="overflow-auto"><table className="media-table"><thead><tr><th>Sahna</th><th>Boshlanish</th><th>Davomiylik</th></tr></thead><tbody>{j.result.timings.map((t,i)=><tr key={i}><td>{t.title}</td><td>{t.start.toFixed(1)} s</td><td>{t.duration.toFixed(1)} s</td></tr>)}</tbody></table></div>}</div>)}
    {saved?.variants.explainer_video_id&&<><video controls className="w-full max-w-sm rounded-xl" src={`/api/media/assets/${saved.variants.explainer_video_id}`}/><a className="media-btn secondary" href={`/api/media/assets/${saved.variants.explainer_video_id}`} download>MP4 yuklab olish</a><p>Article ichiga qo‘shish uchun video faylni o‘sha postga biriktirib, shu HTML ni ishlating:</p><code className="break-all">{`<video src="{{asset:${saved.variants.explainer_video_id}}}"></video>`}</code></>}
    {saved?.variants.explainer_audio_id&&<audio controls src={`/api/media/assets/${saved.variants.explainer_audio_id}`}/>}
    </section>
    {error&&<p role="alert" className="media-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
  </div>;
}
