import { useEffect,useState } from "react";
import { Film,Plus,Sparkles,CalendarDays,Upload,Check,Copy,Download } from "lucide-react";
import { postSchema,type MediaPost,type MediaAsset } from "@shared/media";
import { reelBriefSchema,reelPackageSchema,reelDates,type ReelPackage } from "@shared/reels";
import { qomusReel,qomusCaption } from "@shared/reels-qomus";
import { mediaApi,inputToIso,localInput,tashkentDate,type MediaData } from "./api";
const input="media-input";
type Draft={id?:string;title:string;caption:string;variants:MediaPost['variants'];production_notes:string};
const initial=():Draft=>({title:"Al-Qomus — tuslangan so‘zdan asl fe’lga",caption:qomusCaption,variants:{reels:structuredClone(qomusReel)},production_notes:"Higgsfield 3D kirish + haqiqiy sayt ekranlari + HyperFrames montaj. Umidjon klon, Eleven v4, o‘zbekcha. Yorqin ko‘k/firuza/sariq ranglar, yirik matn, alohida arabcha RTL qatlam, ovozga mos sahnalar, SFX va sokin instrumental fon."});
export default function ReelsStudio({data,onSaved}:{data:MediaData;onSaved:()=>Promise<unknown>}) {
  const [draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState<string[]>([]),[account,setAccount]=useState(''),[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[count,setCount]=useState(12),[topic,setTopic]=useState("Al-Qomusning foydali imkoniyatlarini 12 xil amaliy misolda tushuntirish"),[date,setDate]=useState(localInput()),[status,setStatus]=useState<any>(null),[voices,setVoices]=useState<{id:string;name:string;category:string}[]>([]);
  const posts=data.posts.filter(p=>p.variants.reels);
  const accounts=data.accounts.filter(a=>a.platform==='instagram'&&a.enabled&&a.verified_at);
  useEffect(()=>{if(!account&&accounts[0])setAccount(accounts[0].id);},[accounts.map(a=>a.id).join(',')]);
  useEffect(()=>{let live=true;mediaApi('/reels/status').then(v=>{if(live)setStatus(v)}).catch(()=>{});return()=>{live=false};},[data]);
  const active=draft?.id&&data.jobs.some(j=>['reels_audio','reels_render'].includes(j.kind)&&j.payload?.post_id===draft.id&&['queued','running'].includes(j.status));
  const locked=busy||!!active;
  const reel=draft?.variants.reels;
  async function perform(fn:()=>Promise<unknown>,message:string) {setBusy(true);setError('');setNotice('');try{await fn();await onSaved();setNotice(message);}catch(e){setError(e instanceof Error?e.message:'Amal bajarilmadi.');}finally{setBusy(false);}}
  function update(patch:Partial<ReelPackage>,invalidate=true) {if(!draft||!reel)return;setDraft({...draft,variants:{...draft.variants,reels:{...reel,...patch,...(invalidate?{reviewed:false}:{})}}});}
  async function save(value=draft) {
    if(!value?.variants.reels)throw new Error('Reels loyihasini oching.');
    const r=reelPackageSchema.parse(value.variants.reels);
    const body=postSchema.parse({...value,format:'video',asset_ids:r.video_id?[r.video_id]:[],variants:{...value.variants,reels:r,...(r.video_id?{instagram_asset_ids:[r.video_id]}:{})}});
    const saved=await mediaApi<MediaPost>(value.id?`/posts/${value.id}`:'/posts',value.id?'PATCH':'POST',body);
    setDraft(saved);return saved.id;
  }
  async function upload(file:File|undefined,apply:(id:string)=>void) {
    if(!file)return;
    if(file.size>50*1024*1024)throw new Error('Fayl 50 MB dan oshmasin.');
    const mime=file.type||(/\.mp4$/i.test(file.name)?'video/mp4':/\.mp3$/i.test(file.name)?'audio/mpeg':/\.png$/i.test(file.name)?'image/png':'image/jpeg');
    const response=await fetch('/api/media/assets',{method:'POST',credentials:'same-origin',headers:{'Content-Type':mime,'X-File-Name':encodeURIComponent(file.name)},body:file});
    const asset=await response.json();if(!response.ok)throw new Error(asset.error||'Fayl yuklanmadi.');apply(asset.id);
  }
  const picker=(label:string,mimes:string[],value:string|null|undefined,apply:(id:string|null)=>void)=> <div className="reels-picker"><label className="media-field"><span>{label}</span><select className={input} disabled={locked} value={value||''} onChange={e=>apply(e.target.value||null)}><option value="">Fayl tanlang</option>{data.assets.filter(a=>mimes.includes(a.mime_type)).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="reels-upload"><Upload size={16}/> Yuklash<input aria-label={`${label} yuklash`} type="file" accept={mimes.join(',')} disabled={locked} onChange={e=>{const f=e.target.files?.[0];void perform(()=>upload(f,id=>apply(id)),'Fayl yuklandi. Paketni saqlang.');e.target.value='';}}/></label></div>;
  function exportDraft() {if(!draft)return;const blob=new Blob([JSON.stringify({...draft,id:undefined},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='reels-package.json';a.click();URL.revokeObjectURL(url);}
  return <div className="reels-studio">
    <section className="reels-hero"><div className="reels-eyebrow"><Film size={18}/> INSTAGRAM REELS STUDIYASI</div><h2>Foydali video.<br/><em>Qiziqqan o‘quvchiga havola.</em></h2><p>Ssenariy, klon ovoz, video, cover va avtomatik Direct — bitta paketda.</p><div className="media-actions"><button className="media-btn primary" disabled={locked} onClick={()=>{setDraft(initial());setNotice('Al-Qomus namunasi ochildi.');setError('');}}><Plus size={17}/> Al-Qomus namunasi</button><label className="media-btn"><Upload size={17}/> Chatdan paketni olish<input type="file" accept="application/json,.json" style={{display:'none'}} disabled={locked} onChange={e=>{const f=e.target.files?.[0];if(f)void perform(async()=>{const raw=JSON.parse(await f.text());const p=postSchema.parse({...raw,format:'video'});if(!p.variants.reels)throw new Error('Bu faylda Reels paketi yo‘q.');setDraft({...p});},'Paket ochildi. Media fayllarni biriktirib saqlang.');e.target.value='';}}/></label></div><div className="reels-badges"><span>40–60 soniya</span><span>9:16 · 1080p</span><span>Umidjon klon</span><span>Toshkent vaqti</span></div></section>
    {error&&<div className="media-alert" role="alert">{error}</div>}{notice&&<div className="media-notice" role="status">{notice}</div>}
    <div className="reels-summary"><div><strong>{posts.length}</strong><span>Reels paketi</span></div><div><strong>{posts.filter(p=>p.variants.reels?.reviewed&&p.variants.reels.video_id).length}</strong><span>Nashrga tayyor</span></div><div><strong>{posts.flatMap(p=>p.deliveries).filter(d=>d.status==='scheduled').length}</strong><span>Navbatda</span></div><div><strong>{status?.automations?.reduce((n:number,a:any)=>n+Number(a.links_sent),0)||0}</strong><span>Obunadan keyin havola</span></div></div>
    <section className="media-panel"><div className="reels-section-head"><h2>Video paketlari</h2><span>{posts.length} ta</span></div>
      {posts.length===0?<p>Al-Qomus namunasidan boshlang yoki chatda tayyorlangan paketni yuklang.</p>:<div className="reels-cards">{posts.map(p=>{const r=p.variants.reels!,delivery=p.deliveries.find(d=>d.platform==='instagram'),automation=status?.automations?.find((a:any)=>a.source_delivery_id===delivery?.id);return <article className="reels-card" key={p.id}>
        <div className="reels-card-art">{p.variants.instagram_cover_id?<img src={`/api/media/assets/${p.variants.instagram_cover_id}`} alt={p.title}/>:<Film size={45}/>}<span>{r.actual_seconds?`${r.actual_seconds.toFixed(0)} s`:`${r.target_seconds} s`}</span></div><div className="reels-card-copy"><label><input aria-label={`${p.title} ni tanlash`} type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(e.target.checked?[...selected,p.id]:selected.filter(id=>id!==p.id))}/> <b>{p.title}</b></label><p>{r.hook}</p><div className="reels-keywords">{r.keywords.map(k=><span key={k}>{k}</span>)}</div><small>{delivery?`${delivery.status==='published'?'Nashr qilindi':delivery.status==='scheduled'?'Rejada':delivery.status} · ${tashkentDate(delivery.scheduled_at)}`:r.reviewed&&r.video_id?'Nashrga tayyor':'Tayyorlanmoqda'}</small>{automation&&<small>Direct: {automation.enabled?'faol':'o‘chirilgan'} · {automation.require_follow?'obuna shart':'ochiq'}</small>}<div className="media-actions"><button className="media-btn" disabled={locked} onClick={()=>{setDraft(structuredClone(p));setDate(localInput(p.variants.suggested_at));setError('');}}>Paketni ochish</button><button className="media-btn" disabled={locked} aria-label={`${p.title} nusxasi`} onClick={()=>{setDraft({...structuredClone(p),id:undefined,title:p.title.slice(0,90)+' (nusxa)',variants:{...p.variants,reels:{...r,reviewed:false},suggested_at:undefined}});}}><Copy size={15}/></button></div>{delivery?.external_url&&<a href={delivery.external_url} target="_blank" rel="noreferrer">Instagramda ko‘rish ↗</a>}</div>
      </article>})}</div>}
      <details className="reels-batch"><summary><CalendarDays size={18}/> Tanlangan videolarni birdan rejalash · {selected.length} ta</summary><div className="reels-form-grid"><label className="media-field"><span>Instagram hisob</span><select className={input} value={account} onChange={e=>setAccount(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="media-field"><span>Oy · 18:00 Toshkent</span><input className={input} type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div><p>Faqat ko‘rib chiqilgan, video va coveri tayyor paketlar rejalashtiriladi.</p><button className="media-btn primary" disabled={locked||!selected.length||!account} onClick={()=>void perform(async()=>{const dates=reelDates(month,selected.length);if(dates.length!==selected.length)throw new Error('Bu oyda yetarli kelajak sanasi yo‘q.');await mediaApi('/schedule','POST',{items:selected.map((id,i)=>({post_id:id,scheduled_at:dates[i]})),account_ids:[account]});setSelected([]);},'Tanlangan Reelslar rejalashtirildi.')}><CalendarDays size={16}/> Hammasini rejalash</button></details>
    </section>
    {draft&&reel&&<section className="media-panel reels-editor"><div className="reels-section-head"><h2>Reels paketi</h2><button className="media-btn" onClick={exportDraft}><Download size={16}/> JSON</button></div>
      <div className="reels-form-grid"><label className="media-field"><span>Video nomi</span><input className={input} disabled={locked} value={draft.title} maxLength={100} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="media-field"><span>Kirishdagi hook</span><input className={input} disabled={locked} value={reel.hook} maxLength={220} onChange={e=>update({hook:e.target.value})}/></label></div>
      <label className="media-field"><span>Diktor matni · o‘zbekcha va arabcha</span><textarea className={input} rows={7} disabled={locked} maxLength={2000} value={reel.script} onChange={e=>update({script:e.target.value})}/></label>
      <label className="media-field"><span>Instagram tavsifi</span><textarea className={input} rows={4} disabled={locked} maxLength={2200} value={draft.caption} onChange={e=>setDraft({...draft,caption:e.target.value})}/></label>
      <div className="reels-form-grid"><label className="media-field"><span>Kalit so‘zlar · vergul bilan</span><input className={input} disabled={locked} value={reel.keywords.join(', ')} onChange={e=>update({keywords:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)})}/></label><label className="media-field"><span>Yuboriladigan havola</span><input className={input} type="url" disabled={locked} value={reel.link_url} onChange={e=>update({link_url:e.target.value})}/></label></div>
      <label className="media-field"><span>Directdagi xabar · havola avtomatik qo‘shiladi</span><textarea className={input} rows={2} maxLength={800} disabled={locked} value={reel.dm_text} onChange={e=>update({dm_text:e.target.value})}/></label>
      <div className="reels-switches"><label><input type="checkbox" checked={reel.require_follow} disabled={locked} onChange={e=>update({require_follow:e.target.checked})}/> Havoladan oldin obunani tekshirish</label><label><input type="checkbox" checked={reel.automation_enabled} disabled={locked} onChange={e=>update({automation_enabled:e.target.checked})}/> Nashrdan keyin Direct qoidasini yoqish</label></div><p className="reels-help">Obuna uchun o‘quvchi Directdagi ko‘rsatmaga javob beradi. Tizim Meta orqali tekshiradi; tekshiruv noaniq bo‘lsa, havola berilmaydi.</p>
      <div className="reels-form-grid">{picker('Tayyor Reels MP4',['video/mp4'],reel.video_id,id=>update({video_id:id}))}{picker('Cover JPG',['image/jpeg'],draft.variants.instagram_cover_id,id=>setDraft({...draft,variants:{...draft.variants,instagram_cover_id:id||undefined,reels:{...reel,reviewed:false}}}))}{picker('Diktor audio MP3',['audio/mpeg'],reel.audio_id,id=>update({audio_id:id,audio_fingerprint:''}))}{picker('Higgsfield kirish MP4',['video/mp4'],reel.intro_id,id=>update({intro_id:id}))}</div>
      <div className="media-actions"><button className="media-btn" disabled={locked} onClick={()=>void perform(async()=>{const c=await mediaApi<{voices:typeof voices}>('/audio/catalog');setVoices(c.voices);},'Ovozlar yangilandi.')}>Klon ovozlarni olish</button><select aria-label="Reels diktor ovozi" className={input} style={{maxWidth:380}} value={reel.voice_id} disabled={locked} onChange={e=>update({voice_id:e.target.value})}><option value="Rho2qPfhZy8UjudEdHC2">Umidjon · Klon · uz</option>{voices.filter(v=>v.id!=='Rho2qPfhZy8UjudEdHC2').map(v=><option key={v.id} value={v.id}>{v.name} · {v.category}</option>)}</select><button className="media-btn" disabled={locked||!reel.voice_id} onClick={()=>void perform(async()=>{const id=await save();await mediaApi('/reels/audio','POST',{post_id:id});},'Klon ovoz navbatga qo‘yildi. Jarayon tugagach paketni qayta oching.')}>Klon ovoz yaratish</button></div>
      {reel.audio_id&&<audio controls src={`/api/media/assets/${reel.audio_id}`} className="reels-audio"/>}
      <details><summary>Sahnalar va montaj · {reel.scenes.length} ta</summary>{reel.scenes.map((s,i)=><div className="reels-scene" key={i}><b>{i+1}. {s.kind}</b><div className="reels-form-grid"><label className="media-field"><span>Sahna sarlavhasi</span><input className={input} value={s.title} disabled={locked} maxLength={70} onChange={e=>update({scenes:reel.scenes.map((v,n)=>n===i?{...v,title:e.target.value}:v)})}/></label><label className="media-field"><span>Soniya</span><input type="number" className={input} value={s.seconds} min={3} max={20} step={.5} disabled={locked} onChange={e=>update({scenes:reel.scenes.map((v,n)=>n===i?{...v,seconds:Number(e.target.value)}:v)})}/></label></div><label className="media-field"><span>Arabcha · RTL qatlam</span><input className={input} dir="rtl" value={s.arabic} disabled={locked} onChange={e=>update({scenes:reel.scenes.map((v,n)=>n===i?{...v,arabic:e.target.value}:v)})}/></label><label className="media-field"><span>Qisqa izoh</span><input className={input} value={s.body} disabled={locked} maxLength={180} onChange={e=>update({scenes:reel.scenes.map((v,n)=>n===i?{...v,body:e.target.value}:v)})}/></label>{picker(`${i+1}-sahna rasmi`,['image/jpeg','image/png'],s.image_id,id=>update({scenes:reel.scenes.map((v,n)=>n===i?{...v,image_id:id}:v)}))}</div>)}<label className="media-field"><span>Umumiy davomiylik · sahna vaqtlari yig‘indisiga teng</span><input className={input} type="number" min={40} max={60} value={reel.target_seconds} disabled={locked} onChange={e=>update({target_seconds:Number(e.target.value)})}/></label>{picker('Fon musiqa MP3 · ixtiyoriy',['audio/mpeg'],reel.music_id,id=>update({music_id:id}))}<label className="media-field"><span>Professional vizual prompt va montaj talablari</span><textarea className={input} rows={4} value={draft.production_notes} disabled={locked} onChange={e=>setDraft({...draft,production_notes:e.target.value})}/></label><button className="media-btn" disabled={locked||!reel.audio_id||!reel.intro_id} onClick={()=>void perform(async()=>{const id=await save();await mediaApi('/reels/render','POST',{post_id:id});},'HyperFrames montaji navbatga qo‘yildi. Sahifani ochiq qoldirish shart emas.')}>HyperFrames’da video va cover yaratish</button></details>
      <details><summary>Manba va oylik ssenariylar</summary><label className="media-field"><span>Manba sayt</span><input className={input} type="url" value={reel.source_url} disabled={locked} onChange={e=>update({source_url:e.target.value})}/></label><label className="media-field"><span>Tekshirilgan imkoniyatlar va misollar</span><textarea className={input} rows={4} value={reel.source_notes} disabled={locked} onChange={e=>update({source_notes:e.target.value})}/></label><label className="media-field"><span>Videolar mavzusi va talablari</span><textarea className={input} rows={3} value={topic} onChange={e=>setTopic(e.target.value)}/></label><div className="reels-form-grid"><label className="media-field"><span>Video soni · 1–12</span><input className={input} type="number" min={1} max={12} value={count} onChange={e=>setCount(Number(e.target.value))}/></label><label className="media-field"><span>Oy</span><input className={input} type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div><button className="media-btn" disabled={locked} onClick={()=>void perform(()=>mediaApi('/reels/campaign','POST',reelBriefSchema.parse({...reel,topic,count,month})),`${count} ta ssenariy navbatga qo‘yildi. Video fayllar tayyor bo‘lgach birga rejalang.`)}><Sparkles size={17}/> Oylik ssenariylarni yaratish</button></details>
      {reel.video_id&&<video className="reels-video" controls poster={draft.variants.instagram_cover_id?`/api/media/assets/${draft.variants.instagram_cover_id}`:undefined} src={`/api/media/assets/${reel.video_id}`}/>}
      <label className="reels-ready"><input type="checkbox" checked={reel.reviewed} disabled={locked||!reel.video_id||!draft.variants.instagram_cover_id} onChange={e=>update({reviewed:e.target.checked},false)}/> <Check size={18}/> Video, matn, ovoz va cover ko‘rib chiqildi — nashrga tayyor</label>
      <div className="media-actions"><button className="media-btn primary" disabled={locked} onClick={()=>void perform(()=>save(),'Reels paketi saqlandi.')}>Paketni saqlash</button><label className="media-field"><span>Nashr sanasi · Toshkent</span><input className={input} type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="media-btn" disabled={locked||!reel.reviewed||!account} onClick={()=>void perform(async()=>{const id=await save();await mediaApi(`/posts/${id}/schedule`,'POST',{account_ids:[account],scheduled_at:inputToIso(date)});setDraft(null);},'Reels rejalashtirildi. Nashrdan keyin Direct qoidasini tizim o‘zi bog‘laydi.')}>Rejalashtirish</button></div>
    </section>}
    {data.jobs.filter(j=>j.kind.startsWith('reels_')).length>0&&<section className="media-panel"><h2>Jarayonlar</h2>{data.jobs.filter(j=>j.kind.startsWith('reels_')).map(j=><div className="reels-job" key={j.id}><b>{j.kind==='reels_plan'?'Ssenariylar':j.kind==='reels_audio'?'Klon ovoz':'HyperFrames video'}</b><span>{j.status==='queued'?'Navbatda':j.status==='running'?'Tayyorlanmoqda':j.status==='completed'?'Tayyor':'Xato'}</span>{j.error&&<p role="alert">{j.error}</p>}</div>)}</section>}
  </div>;
}
