import type { Express } from "express";

const supportEmail = "umidjonabdurayimov04@gmail.com";
const updated = "6-oktabr 2026 / 6 October 2026";
const origin = "https://web-production-d1f0.up.railway.app";
const deletionMail = `mailto:${supportEmail}?subject=${encodeURIComponent("Zamonaviy Media Agent — ma’lumotlarni o‘chirish / Data deletion")}&body=${encodeURIComponent("Instagram username: @\nProfil havolasi / Profile URL: \nO‘chirish so‘rovi / Deletion request: Zamonaviy Media Agent saqlagan menga tegishli izohlar va Direct ma’lumotlarini o‘chirishingizni so‘rayman. / Please delete my comments and Direct message data stored by Zamonaviy Media Agent.")}`;

const privacy = `
  <div class="intro"><p>Zamonaviy Media Agent — Umidjon Abdurayimov boshqaradigan shaxsiy kontent va ijtimoiy tarmoqlar yordamchisi. Ushbu siyosat ilovaning Instagram va boshqa ulangan xizmatlar orqali oladigan ma’lumotlariga tegishli.</p><a class="language" href="#english" lang="en">Read in English ↓</a></div>
  <section><h2>1. Qanday ma’lumotlar olinadi?</h2><ul>
    <li><strong>Ulangan hisob:</strong> platformadagi hisob ID si, profil nomi, ulanish holati va ruxsat berilgan profil yoki media ma’lumotlari.</li>
    <li><strong>Instagram izohlari va Direct:</strong> ulangan sahifaga kelgan izoh yoki matnli xabar, uni yuborgan foydalanuvchining platforma ID si, xabar/izoh ID si, tegishli post ID si va vaqti. Javob yuborilganligi yoki xatolik holati ham saqlanishi mumkin.</li>
    <li><strong>Kontent va statistika:</strong> administrator yuklagan rasm, video, audio, post matni va jadvali; ruxsat berilgan ko‘rish, qamrov, like, izoh, saqlash va ulashish ko‘rsatkichlari.</li>
    <li><strong>Ulanish va xavfsizlik:</strong> API tokenlari, ilova ulanish sirlari, administrator sessiyasi va xizmatning texnik jurnallari. Hosting jurnallarida IP manzil, so‘rov manzili, vaqt va javob holati bo‘lishi mumkin.</li>
  </ul><p>Ilova Instagram yoki Facebook parolini saqlamaydi. Ushbu axborot sahifalarini o‘qish uchun hisobga kirish talab qilinmaydi.</p></section>
  <section><h2>2. Ma’lumotlar nima uchun ishlatiladi?</h2><p>Hisobni ulash va tekshirish, tayyor kontentni rejalash va nashr qilish, kelgan izoh yoki Direct xabarini boshqaruv panelida ko‘rsatish, administrator yoqqan javob qoidalarini bajarish, post natijalarini tahlil qilish va xizmat xavfsizligini ta’minlash uchun.</p><p>Avtomatik javoblar administrator belgilagan kalit so‘z va tayyor javoblarga asoslanadi. Ular yoqilgan qoidalarga qarab ishlaydi. Hozirgi Direct yordamchisi kelgan har bir xabarni generativ AI ga avtomatik yubormaydi.</p></section>
  <section><h2>3. Kimlar bilan ma’lumot almashiladi?</h2><p>Ma’lumotlarni vakolatli administrator va xizmatni ishlatish uchun kerakli provayderlar qayta ishlaydi: Railway — hosting va ma’lumotlar bazasi; Meta/Instagram, Telegram va YouTube — administrator ulagan platformalarda nashr va tegishli amallar.</p><p>Administrator kontent yaratish yoki tekshirishni ishga tushirganda, tanlangan matn yoki material OpenAI xizmatiga yuborilishi mumkin. Audio yaratishda o‘qiladigan matn va tanlangan ovoz identifikatori ElevenLabs xizmatiga yuboriladi. Nashr uchun mo‘ljallangan media platformaga taqdim etiladi va nashr qilingan kontent ommaga ko‘rinadi. Provayderlar ma’lumotlarni o‘z siyosatlariga muvofiq qayta ishlaydi; ular boshqa mamlakatlarda ishlashi mumkin.</p><p>Ilova foydalanuvchi ma’lumotlarini sotish uchun mo‘ljallanmagan.</p></section>
  <section><h2>4. Saqlash va himoya</h2><p>Ma’lumotlar hisobni yuritish, kontentni boshqarish va murojaatlarga javob berish uchun zarur davr davomida saqlanadi. Barcha yozuvlar uchun yagona avtomatik o‘chirish muddati belgilanmagan; o‘chirish so‘rovlarini administrator qo‘lda ko‘rib chiqadi. Hosting jurnallari va provayder nusxalarining saqlanishi ularning tartibiga bog‘liq.</p><p>Boshqaruv paneli autentifikatsiya bilan himoyalangan. Ulanish tokenlari va sirlari bazada shifrlanadi; HTTPS ulanishi ishlatiladi. Administratorga kirishda zarur sessiya cookie si qo‘llanadi. Bu ikki axborot sahifasi alohida kuzatuv skripti yoki reklama cookie sini o‘rnatmaydi.</p></section>
  <section class="highlight"><h2>5. Ma’lumotlaringizni o‘chirish yoki tuzatish</h2><p>Har qanday foydalanuvchi o‘ziga tegishli ma’lumotlar haqida so‘rashi, ularni tuzatish yoki o‘chirishni talab qilishi mumkin. <a href="/data-deletion">O‘chirish yo‘riqnomasi</a> bo‘yicha murojaat qiling yoki <a href="mailto:${supportEmail}">${supportEmail}</a> manziliga yozing.</p><p>So‘rov egasini tasdiqlash uchun profil havolasi yoki o‘sha hisobdan tasdiq kerak bo‘lishi mumkin. Parol, SMS kodi yoki API tokenini yubormang. Ilovadagi nusxani o‘chirish Instagram hisobingizni yoki platformadagi asl post va xabarlarni o‘chirmaydi.</p></section>
  <section><h2>6. Aloqa va yangilanishlar</h2><p>Mas’ul: <strong>Umidjon Abdurayimov — Zamonaviy Media Agent.</strong><br>Aloqa: <a href="mailto:${supportEmail}">${supportEmail}</a>.</p><p>Xizmat o‘zgarganda siyosat shu manzilda yangilanadi va yangilanish sanasi ko‘rsatiladi.</p></section>
  <section id="english" lang="en" class="english"><span class="eyebrow">ENGLISH</span><h2>Privacy Policy</h2>
    <p>Zamonaviy Media Agent is a personal content and social media assistant operated by Umidjon Abdurayimov. This policy covers information processed by this application through Instagram and its connected services.</p>
    <h3>Information and purposes</h3><p>We process connected account IDs and profile names, authorized profile/media information, connection status, and access credentials. For Instagram comments and text messages received by the connected account, we may store the sender’s platform ID, comment/message ID, text, related media ID, timestamps and reply/error status. We also process administrator-provided content, publication schedules, authorized post metrics, administrative sessions and technical logs. Hosting logs may contain IP addresses, request paths, times and response status. We do not store Instagram or Facebook passwords.</p>
    <p>This information is used to connect accounts, schedule and publish content, show incoming interactions to the administrator, carry out enabled response rules, measure post performance and secure the service. Current automated Direct responses use administrator-defined keywords and approved text; incoming messages are not automatically sent to generative AI.</p>
    <h3>Service providers and sharing</h3><p>Authorized administrators and necessary service providers process data: Railway for hosting/database, and Meta/Instagram, Telegram and YouTube for enabled platform operations. When the administrator starts content generation or review, selected material may be sent to OpenAI. Narration text and the selected voice ID are sent to ElevenLabs when audio generation is requested. Publication media is provided to the destination platform; published content is public. Providers process data under their own policies and may operate in other countries. The application is not intended to sell user data.</p>
    <h3>Retention and security</h3><p>Records are retained while needed to manage the connected account, content and interactions. There is no single automatic expiry for all records; the administrator handles deletion requests manually. Provider logs and backup retention depend on the provider. The admin panel requires authentication, connection credentials are encrypted in the database, HTTPS is used, and admin login uses a necessary session cookie. These information pages contain no separate tracking scripts or advertising cookies.</p>
    <h3>Your choices and contact</h3><p>All users may request access, correction or deletion of their own application data by following the <a href="/data-deletion#english">data deletion instructions</a> or emailing <a href="mailto:${supportEmail}">${supportEmail}</a>. We may ask for a profile link or confirmation from that account to verify ownership. Never send passwords, login codes or access tokens. Deletion of application records does not delete your Instagram account or original platform content. Policy changes are published on this page with an updated date.</p>
  </section>`;

const deletion = `
  <div class="intro"><p>Zamonaviy Media Agent saqlagan o‘zingizga tegishli ma’lumotlarni o‘chirishni quyidagi tartibda so‘rashingiz mumkin. Bu murojaat qilish yo‘riqnomasi; sahifani ochishning o‘zi ma’lumotlarni o‘chirmaydi.</p><a class="language" href="#english" lang="en">Read in English ↓</a></div>
  <section><h2>1. So‘rov yuboring</h2><p><a href="mailto:${supportEmail}">${supportEmail}</a> manziliga xat yozing. Xat mavzusi:</p><div class="template">Zamonaviy Media Agent — ma’lumotlarni o‘chirish</div><p>Xatda quyidagilarni ko‘rsating:</p><ul><li>Instagram foydalanuvchi nomingiz va profil havolasi.</li><li>Qaysi yozuvlarni o‘chirishni xohlayotganingiz: izohlar, Direct xabarlari yoki sizga tegishli boshqa ilova ma’lumotlari.</li><li>Zarur bo‘lsa, tegishli post havolasi yoki taxminiy xabar sanasi.</li></ul><a class="button" href="${deletionMail}">Email orqali so‘rov yozish ↗</a><p class="muted">Tugma qurilmangizdagi email dasturini ochadi. U ochilmasa, yuqoridagi manzilga o‘zingiz xat yuboring.</p></section>
  <section><h2>2. Hisob egasi ekaningiz tasdiqlanadi</h2><p>Administrator murojaatni qo‘lda ko‘rib chiqadi. Ma’lumot begona odamning so‘rovi bilan o‘chirilmasligi uchun sizdan o‘sha Instagram hisobidan tasdiq yoki qo‘shimcha aniqlik so‘ralishi mumkin.</p><div class="highlight"><strong>Parol, SMS kodi, bank karta ma’lumoti yoki API tokenini yubormang.</strong> So‘rov uchun ular kerak emas.</div></section>
  <section><h2>3. Ilovadagi tegishli yozuvlar o‘chiriladi</h2><p>Tasdiqlangan so‘rov bo‘yicha sizga bog‘langan izoh va Direct nusxalari, platforma identifikatorlari hamda javob holati yozuvlari faol ilova bazasidan o‘chiriladi. Ulangan hisobning egasi ulanishni ham bekor qilishni so‘rasa, uning ulanish ma’lumotlari va tokenlari ham so‘rov doirasida o‘chiriladi. Natija haqida murojaat qilgan manzilingizga javob beriladi.</p><p>So‘rovga tegishli bo‘lmagan boshqa foydalanuvchi yoki administrator kontenti o‘chirilmaydi. Sizga tegishli yuklangan media bo‘lsa, uni ham xatda aniq ko‘rsating. Texnik jurnallar, provayderlar nusxalari yoki qonuniy asos bilan saqlanishi zarur ma’lumotlar bo‘yicha cheklov bo‘lsa, administrator sizga tushuntiradi.</p></section>
  <section class="highlight"><h2>Instagram hisobingiz saqlanadi</h2><p>Bu jarayon Instagram hisobingizni, postlaringizni yoki Instagramdagi asl izoh/xabarlarni o‘chirmaydi. Platformadagi kontentni uning o‘z vositalari bilan boshqarasiz. Ilova ruxsatini Instagram yoki Meta hisob sozlamalari orqali bekor qilish mumkin; ruxsatni bekor qilish ilovada oldin saqlangan nusxalarni avtomatik o‘chirmaydi, shuning uchun yuqoridagi so‘rovni ham yuboring.</p></section>
  <section><h2>Aloqa</h2><p><strong>Umidjon Abdurayimov — Zamonaviy Media Agent.</strong><br><a href="mailto:${supportEmail}">${supportEmail}</a></p><p><a href="/privacy">Maxfiylik siyosatini o‘qish →</a></p></section>
  <section id="english" lang="en" class="english"><span class="eyebrow">ENGLISH</span><h2>Data Deletion Instructions</h2><p>Any user may request deletion of their own data stored by Zamonaviy Media Agent. Opening this page does not submit a request or delete any records.</p><ol>
    <li><strong>Send an email</strong> to <a href="mailto:${supportEmail}">${supportEmail}</a> with the subject “Zamonaviy Media Agent — Data deletion”. Include your Instagram username and profile URL, the records you want deleted (comments, Direct messages or other application data), and a relevant post URL or approximate message date if useful.</li>
    <li><strong>Confirm account ownership.</strong> The administrator reviews requests manually and may ask for confirmation from the affected Instagram account or further clarification. Never send a password, SMS code, payment details or API token.</li>
    <li><strong>Receive a response.</strong> After verification, associated comment/message copies, platform identifiers and response records are removed from the active application database. A connected account owner may also request removal of their connection credentials and tokens. Specify any uploaded media you own. We reply to your request with the outcome and explain any limitations involving technical logs, provider copies or legally required retention. Other users’ data and unrelated administrator content are not deleted.</li>
  </ol><p>This process does not delete your Instagram account or original posts/comments/messages on Instagram. Revoking app access in Instagram or Meta account settings stops authorized access but does not automatically erase previously stored application records; send the deletion request as well.</p><p>Operator: Umidjon Abdurayimov. See our <a href="/privacy#english">Privacy Policy</a>.</p></section>`;

function page(kind: "privacy" | "data-deletion") {
  const isPrivacy = kind === "privacy";
  const title = isPrivacy ? "Maxfiylik siyosati" : "Ma’lumotlarni o‘chirish";
  const englishTitle = isPrivacy ? "Privacy Policy" : "Data Deletion Instructions";
  return `<!doctype html><html lang="uz"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Zamonaviy Media Agent</title><meta name="description" content="${englishTitle} — Zamonaviy Media Agent. Umidjon Abdurayimov. Ma’lumotlardan foydalanish va murojaat tartibi."><link rel="canonical" href="${origin}/${kind}"><style>
  :root{color-scheme:light;--ink:#123c3a;--muted:#536d69;--line:#dbe6e1;--teal:#127b66}*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:24px}body{margin:0;background:#f3f6f2;color:var(--ink);font:17px/1.75 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a{color:#086c58;text-decoration-thickness:1px;text-underline-offset:3px;overflow-wrap:anywhere}a:focus-visible{outline:3px solid #dfa931;outline-offset:5px}.top{background:#123c3a;color:#fff}.top-inner{max-width:1060px;margin:auto;padding:22px 32px;display:flex;align-items:center;justify-content:space-between;gap:24px;flex-wrap:wrap}.brand{display:flex;align-items:center;gap:14px;color:#fff;text-decoration:none;font-weight:700;line-height:1.3}.logo{display:grid;place-items:center;width:44px;height:44px;background:#a9ebcd;color:#123c3a;border-radius:14px;font-size:24px}.brand small{display:block;letter-spacing:.13em;font-size:10px;font-weight:500;margin-top:4px}.top nav{display:flex;gap:18px;flex-wrap:wrap;font-size:14px}.top nav a{color:#d1e6dd;text-decoration:none}.top nav a[aria-current=page]{color:#fff;text-decoration:underline}main{max-width:960px;padding:44px 32px 64px;margin:auto}.eyebrow{font-size:12px;letter-spacing:.14em;font-weight:750;color:var(--teal)}h1{font-size:clamp(30px,5vw,45px);line-height:1.2;letter-spacing:-.03em;margin:12px 0}header>p{color:var(--muted);margin:8px 0}.updated{font-size:13px;margin-top:18px}.document{background:#fff;border:1px solid var(--line);border-radius:22px;padding:36px 40px;margin-top:28px;box-shadow:0 10px 32px #173a2910}section{margin-top:32px}h2{font-size:22px;line-height:1.4;margin:0 0 12px}h3{font-size:18px;margin-top:24px}p{margin:0 0 14px}ul,ol{padding-left:24px;margin:12px 0}li{padding-left:4px;margin:10px 0}.intro{font-size:18px}.language{font-size:14px}.highlight{border:1px solid #b8dfcd;background:#eff8f1;border-radius:14px;padding:22px}.template{border:1px solid var(--line);border-radius:12px;padding:15px 18px;background:#f5f8f5;overflow-wrap:anywhere}.button{display:inline-block;background:var(--teal);color:#fff;text-decoration:none;font-weight:650;border-radius:12px;padding:12px 20px;margin:8px 0 14px}.muted{color:var(--muted);font-size:14px}.english{border-top:2px solid var(--line);padding-top:30px}.english h2{margin-top:8px}.footer{margin-top:28px;display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;font-size:13px;color:var(--muted)}@media(max-width:600px){body{font-size:16px}.top-inner{padding:18px 20px;gap:18px}main{padding:30px 16px 44px}.document{padding:24px 20px;border-radius:16px}h2{font-size:20px}.highlight{padding:18px}.top nav{font-size:13px}.intro{font-size:17px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
  </style></head><body><div class="top"><div class="top-inner"><a class="brand" href="/privacy"><span class="logo" aria-hidden="true">Z</span><span>Zamonaviy<small>MEDIA AGENT</small></span></a><nav aria-label="Axborot sahifalari"><a href="/privacy" ${isPrivacy ? 'aria-current="page"' : ""}>Maxfiylik</a><a href="/data-deletion" ${!isPrivacy ? 'aria-current="page"' : ""}>Ma’lumotlarni o‘chirish</a></nav></div></div><main><header><span class="eyebrow">ZAMONAVIY MEDIA AGENT</span><h1>${title}</h1><p lang="en">${englishTitle}</p><p class="updated">Yangilangan / Updated: <time datetime="2026-10-06">${updated}</time></p></header><article class="document">${isPrivacy ? privacy : deletion}</article><footer class="footer"><span>Zamonaviy Ta’lim · Umidjon Abdurayimov</span><a href="mailto:${supportEmail}">Aloqa / Contact</a></footer></main></body></html>`;
}

/** Public HTML is readable without JavaScript, credentials or API/database calls. */
export function registerMediaPublicPages(app: Express) {
  for (const kind of ["privacy", "data-deletion"] as const) {
    const html = page(kind);
    app.get(`/${kind}`, (_req, res) => {
      res.set({
        "Cache-Control": "public, max-age=60",
        "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'",
        "X-Content-Type-Options": "nosniff",
        "Referrer-Policy": "no-referrer",
      });
      res.status(200).type("html").send(html);
    });
  }
}
